=== leezm/Java/在校的时候的Java实例/JavaSE(swing组件为主)/1030 xml什么的/Lee/com/students.dtd
<?xml version="1.0" encoding="gb2312"?>
<!ELEMENT Students (Student*)>
<!ELEMENT Student (Student_ID,Student_Name,Student_Sex,Student_Age)>
<!ELEMENT Student_ID (#PCDATA)>
<!ELEMENT Student_Name (#PCDATA)>
<!ELEMENT Student_Sex (#PCDATA)>
<!ELEMENT Student_Age (#PCDATA)>

=== leezm/Java/在校的时候的Java实例/JavaSE(swing组件为主)/1030 xml什么的/Lee/com/students.xml
<?xml version="1.0" encoding="gb2312"?>
<!DOCTYPE Students SYSTEM "bin\\Lee\\com\\Students.dtd">
<Students>
	<Student>
		<Student_ID>001</Student_ID>
		<Student_Name>ÕÅÇì±ó</Student_Name>
		<Student_Sex>ÄÐ</Student_Sex>
		<Student_Age>20</Student_Age>
	</Student>
	<Student>
		<Student_ID>002</Student_ID>
		<Student_Name>ÈÎÊ÷Èº</Student_Name>
		<Student_Sex>ÄÐ</Student_Sex>
		<Student_Age>21</Student_Age>
	</Student>
	<Student>
		<Student_ID>003</Student_ID>
		<Student_Name>·ëºñ¿í</Student_Name>
		<Student_Sex>ÄÐ</Student_Sex>
		<Student_Age>21</Student_Age>
	</Student>
	<Student>
		<Student_ID>004</Student_ID>
		<Student_Name>Áõ±´±´</Student_Name>
		<Student_Sex>ÄÐ</Student_Sex>
		<Student_Age>21</Student_Age>
	</Student>
</Students>
